replicaCount: 1

podAnnotations:
  fluenbit.io/exclude: "true"

image:
  repository: azureks.azurecr.io/kube-tools/net-scheduler-worker
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: "net-scheduler-worker"
fullnameOverride: "net-scheduler-worker"

environment:
  envFrom:
    - secretName: kasa-env
  
serviceAccount:
  create: true
  name: "net-scheduler-worker"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 75m
    memory: 175Mi
  requests:
    cpu: 50m
    memory: 125Mi
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80