replicaCount: 1

image:
  repository: azureks.azurecr.io/kube-tools/net-scheduler-worker
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: "net-scheduler-worker"
fullnameOverride: "net-scheduler-worker"

environment:
  environmentVariables: []
  environmentSecrets:
    - name: az-client-id
      key: AZURE_CLIENT_ID
    - name: az-client-secret
      key: AZURE_CLIENT_SECRET
    - name: az-tenant-id
      key: AZURE_TENANT_ID

  
serviceAccount:
  create: true
  name: "net-scheduler-worker"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80