replicaCount: 1

podAnnotations:
  fluenbit.io/exclude: "true"

image:
  repository: azureks.azurecr.io/kube-tools/net-scheduler
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: "net-scheduler"
fullnameOverride: "net-scheduler"

environment:
  environmentVariables: []
  environmentSecrets:
    - name: az-client-id
      key: AZURE_CLIENT_ID
    - name: az-client-secret
      key: AZURE_CLIENT_SECRET
    - name: az-tenant-id
      key: AZURE_TENANT_ID
   
probes:
  endpoints:
    liveness: "/api/health/alive"
    readiness: "/api/health/ready"
  initialDelay: 5
  interval: 10
  timeout: 120
  
serviceAccount:
  create: true
  name: "net-scheduler"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 60m
    memory: 120Mi
  requests:
    cpu: 30m
    memory: 60Mi
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80